# Generated by Django 3.0.6 on 2020-06-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='level',
        ),
    ]
