# Generated by Django 3.0.6 on 2020-06-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_agent_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
