# Generated by Django 3.0.6 on 2020-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupuser',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(default=1, max_length=20, verbose_name='Level'),
            preserve_default=False,
        ),
    ]
