# Generated by Django 3.0.6 on 2020-06-13 09:45

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200612_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='arquivado',
            field=models.BooleanField(verbose_name='Filed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(max_length=20, validators=[api.models.validation_log_levels], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinValueValidator(8)], verbose_name='Password'),
        ),
    ]
